server:
  port: 8888

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: custom-r1
            uri: http://localhost:8081/
            predicates:
              - path=/customers/**
          - id:
            uri: http://localhost:8082/
            predicates:
              - path=/accounts/**
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

  application:
    name: gateway-service
    discovery:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone=http: //localhost:8761/eureka


